[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ["ds-test/=lib/ds-test/src/","@openzeppelin/contracts=node_modules/@openzeppelin/contracts"]
# See more config options https://github.com/gakonst/foundry/tree/master/configr
optimizer = true
optimizer_runs = 200
solc-version = "0.8.10"
verbosity = 4
