[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ["ds-test/=lib/ds-test/src/","@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
# See more config options https://github.com/gakonst/foundry/tree/master/configr
optimizer = true
optimizer_runs = 200
solc-version = "0.8.17"
verbosity = 4

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrum-rinkeby = "${ARBITRUM_RINKEBY_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"

[etherscan]
arbitrum = { key = "${ETHERSCAN_KEY}" }
arbitrum-rinkeby = { key = "${ETHERSCAN_KEY}" }
goerli = { key = "${ETHERSCAN_KEY}" }
