[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./broadcast"}]
remappings = ["ds-test/=lib/ds-test/src/","@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
# See more config options https://github.com/gakonst/foundry/tree/master/configr
optimizer = true
optimizer_runs = 200
solc-version = "0.8.17"
verbosity = 4

[rpc_endpoints]
local = "http://localhost:8545"
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrum-goerli = "${ARBITRUM_GOERLI_RPC_URL}"
wallaby = "https://wallaby.node.glif.io/rpc/v1"

[etherscan]
arbitrum = { key = "${ETHERSCAN_KEY}" }
arbitrum-goerli = { key = "${ETHERSCAN_KEY}" }
