name: Format, Lint, Gas snapshot

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Build and print contract sizes
        run: forge build --sizes

      - name: Check formatting
        run: forge fmt --check

      - name: Check gas snapshots
        run: forge snapshot --tolerance 5 --check # Allow 5% deviation in gas snapshot

      - run: rm pnpm-lock.yaml

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
